coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach, diff, flags, files, tests"
  behavior: default

flags:
  tests:
    paths:
      - plugin/build/test-results/test
