name: PoVerCat CI Build

on:
  workflow_dispatch:

  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

permissions:
  actions: read
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Run build with Gradle Wrapper
        run: ./gradlew build --no-daemon

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ github.ref_name == 'main' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: the13haven/povercat-plugin
          files: build/reports/coverage/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test reports to Codecov
        uses: codecov/test-results-action@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: the13haven/povercat-plugin
          flags: tests
          directory: plugin/build/test-results/test
          fail_ci_if_error: true

  fossa-scan:

    if: ${{ github.ref_name == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: FOSSA Scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          project: povercat-plugin

      - name: FOSSA Test
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          project: povercat-plugin
          run-tests: true